#pragma once

// #include "adjacent_triangle_after.hpp"
#include "adjacent_triangle_count.hpp"
#include "adjacent_triangle.hpp"
#include "area.hpp"
#include "barycenter.hpp"
#include "edge_count.hpp"
#include "index.hpp"
#include "is_ghost.hpp"
#include "mesh.hpp"
// #include "opposite_vertex.hpp"
#include "proxy.hpp"
// #include "substitute_adjacent_triangle.hpp"
#include "topology.hpp"
#include "vertex_count.hpp"
#include "vertex.hpp"
#include "vertices.hpp"
